name: 'Tina Charles '
favicon: null
layout_spectrum: 0.7924224755261093
typography_spectrum: 0.37037652684375644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8327571728732437
  lightness: 0.5557827441953123
  saturation: 0.7779599123168737
  rhythmicContrast: 0.6653554802760482
purpose: []
