typography_spectrum: 0.37037652684375644
color:
  brandColors:
    - '#000201'
    - '#ffffff'
    - '#f4002a'
    - '#f68951'
    - '#6b94b5'
  brandStrength: 0.8327571728732437
  lightness: 0.5557827441953123
  saturation: 0.7779599123168737
  rhythmicContrast: 0.6653554802760482
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7924224755261093
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Tina Charles '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Tian Charles
purpose: []
